env:
  browser: true
  commonjs: true
  es2020: true
extends:
  - google
parserOptions:
  ecmaVersion: 11
rules:
  linebreak-style:
    - 0
  max-len:
    - 2
    - 120
  new-cap:
    - 0
  require-jsdoc:
    - 0
