openapi: 3.0.1
info:
  title: koa-starter
  version: 1.0.0
servers:
  - url: /api
    description: Exposed only for development purposes
components:
  securitySchemes:
    CookieToken:
      type: apiKey
      in: cookie
      name: koa:session
security:
  - CookieToken: []
paths:
  /:
    get:
      summary: Hello World endpoint
      description: Simple endpoint used to test if the server is running
      security: []
      responses:
        "200":
          description: OK

  /authenticated:
    get:
      summary: Hello World authenticated endpoint
      description: Simple endpoint used to test if the server is running and the authentication works
      security:
        - CookieToken: []
      responses:
        "200":
          description: OK

  /user/login/local:
    post:
      tags: [ user ]
      summary: Executes login or registration with email and password
      description: Returns a cookie used for stateless authentication
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      security: [ ]
      responses:
        "200":
          description: OK

  /user/login/google:
    get:
      tags: [ user ]
      summary: Executes Google OAuth2 login or registration process
      description: Returns a cookie used for stateless authentication
      security: [ ]
      responses:
        "200":
          description: OK

  /user/login/facebook:
    get:
      tags: [ user ]
      summary: Executes Facebook OAuth2 login or registration process
      description: Returns a cookie used for stateless authentication
      security: [ ]
      responses:
        "200":
          description: OK

  /user/logout:
    post:
      tags: [ user ]
      summary: Executes logout procedure
      description: Forces authentication cookie removal on the client
      security:
        - CookieToken: []
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                message:
                  type: string
                example:
                  message: Logged out